USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB_PARTIE_1;

CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB_PARTIE_1.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB_PARTIE_1.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB_PARTIE_1.FINAL;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
