USE ROLE ACCOUNTADMIN;
USE DATABASE NYC_TAXI_DB_PARTIE_1;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT TLC_PARQUET_FORMAT
    TYPE = PARQUET;

CREATE STAGE IF NOT EXISTS TLC_RAW_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'NYC_TAXI_DB_PARTIE_1.RAW.TLC_PARQUET_FORMAT');

CREATE TABLE IF NOT EXISTS YELLOW_TAXI_RAW (
    VENDORID NUMBER,
    TPEP_PICKUP_DATETIME NUMBER,
    TPEP_DROPOFF_DATETIME NUMBER,
    PASSENGER_COUNT FLOAT,
    TRIP_DISTANCE FLOAT,
    RATECODEID NUMBER,
    STORE_AND_FWD_FLAG VARCHAR,
    PULOCATIONID NUMBER,
    DOLOCATIONID NUMBER,
    PAYMENT_TYPE NUMBER,
    FARE_AMOUNT FLOAT,
    EXTRA FLOAT,
    MTA_TAX FLOAT,
    TIP_AMOUNT FLOAT,
    TOLLS_AMOUNT FLOAT,
    IMPROVEMENT_SURCHARGE FLOAT,
    TOTAL_AMOUNT FLOAT,
    CONGESTION_SURCHARGE FLOAT,
    AIRPORT_FEE FLOAT,
    CBD_CONGESTION_FEE FLOAT
);
