USE ROLE ACCOUNTADMIN;
USE DATABASE NYC_TAXI_DB_PARTIE_1;
USE SCHEMA RAW;

LIST @TLC_RAW_STAGE;

COPY INTO YELLOW_TAXI_RAW
FROM @TLC_RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = 'NYC_TAXI_DB_PARTIE_1.RAW.TLC_PARQUET_FORMAT')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS raw_rows FROM YELLOW_TAXI_RAW;
