USE ROLE ACCOUNTADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PUBLIC;

GRANT USAGE ON DATABASE NYC_TAXI_DB_PARTIE_1 TO ROLE PUBLIC;
GRANT CREATE SCHEMA ON DATABASE NYC_TAXI_DB_PARTIE_1 TO ROLE PUBLIC;

GRANT USAGE ON SCHEMA NYC_TAXI_DB_PARTIE_1.RAW TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA NYC_TAXI_DB_PARTIE_1.STAGING TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA NYC_TAXI_DB_PARTIE_1.FINAL TO ROLE PUBLIC;

GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_DB_PARTIE_1.RAW TO ROLE PUBLIC;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB_PARTIE_1.RAW TO ROLE PUBLIC;

GRANT CREATE TABLE ON SCHEMA NYC_TAXI_DB_PARTIE_1.STAGING TO ROLE PUBLIC;
GRANT CREATE TABLE ON SCHEMA NYC_TAXI_DB_PARTIE_1.FINAL TO ROLE PUBLIC;
